### ISSUE TITLE
Always show images tab on results page (configurable)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#268] opened 2018-06-26 07:01 UTC
Currently, the results page will only show the "images" tab if the "multimedia" facet is selected and there are images in the resulting search. As a consequence, the images tab disappears if the user deselects `multimedia` from the "customise filters" popup modal - which is unintuitive.

Fix is to always show the images tab (make it dependent on a config var so other portal providers can remove it if they don't have any images in their database). When populating the image body, it should request the images whether or not the facet is requested (see above). If no images found, then display a simple text message (i18n coded).

**Comment by javier-molina** [comment] 2018-06-26 07:04
Duplicate of #267

**Closed by javier-molina** 2018-06-26 07:04 UTC
Labels: enhancement
