### ISSUE TITLE
Sound player on record page not showing play icon

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-hubs#276] opened 2018-09-07 02:21 UTC
Sound file records use a mdeia player JS tool but the play icon is missing, resulting in confusion to the user. See ~~https://biocache.ala.org.au/occurrences/c51ef007-f3a9-4342-82bf-908f92343dbf~~ https://biocache.ala.org.au/occurrences/dad63624-a88a-42d4-9c96-b020c549e0b4

![image](https://user-images.githubusercontent.com/532845/45194849-3b08b680-b298-11e8-944f-4200da5706f0.png)

There should be a triangle shaped icon in the left square region of the sound player. The CSS that loads the image as a background-image appears to be broken:

```
<p class="play"></p>
```

has CSS:

```
.audiojs .play {
    background: url(undefinedplayer-graphics.gif) -2px -1px no-repeat;
}
```

I think the "undefinedplayer" string is the problem.

**Comment by ansell** [comment] 2018-09-07 02:51
If users query about this, they may do so with the error from the flash cache, which looks like this:

**Comment by ansell** [comment] 2018-09-07 03:00
I can replicate the issue on biocache, avh, asbp, and ozcam, but not mdba. mdba-hub is using biocache-hubs-1, so the regression is somewhere in biocache-hubs-2. 

We haven't had testing of sound pages on our manual test lists, so we would need to do a few deployments of previous hubs versions to test servers to narrow the regression range down further.

**Comment by nickdos** [comment] 2020-03-20 06:05
Broke again - re-opening.

**Comment by nickdos** [comment] 2020-03-26 05:03
Safari is not loading images but I think this is due to image-service providing a mime-type of `image/jpeg` instead of a sound type. Already an issue for it https://github.com/AtlasOfLivingAustralia/image-service/issues/109

**Comment by ansell** [comment] 2020-03-29 22:45
An example this working for me in Firefox is:

https://biocache-test.ala.org.au/occurrences/dad63624-a88a-42d4-9c96-b020c549e0b4

The play button on that record in production is broken for me in Firefox:

https://biocache.ala.org.au/occurrences/dad63624-a88a-42d4-9c96-b020c549e0b4

**Comment by ansell** [comment] 2020-03-29 22:46
Moving this to "Ready for CAB" on the basis that the Safari bug is being dealt with separately and will not block publishing this fix. Move it back to QA if that isn't the case.

**Closed** 2020-04-28 04:46 UTC
Labels: IAD, bug
